var hole = $('.hole');

var diag = [
    [
        hole.eq(0),
        hole.eq(7),
        hole.eq(14),
        hole.eq(21)
    ],
    [
        hole.eq(1),
        hole.eq(8),
        hole.eq(15),
        hole.eq(22)
    ],
    [
        hole.eq(2),
        hole.eq(9),
        hole.eq(16),
        hole.eq(23)
    ],
    [
        hole.eq(3),
        hole.eq(8),
        hole.eq(13),
        hole.eq(18)
    ],
    [
        hole.eq(4),
        hole.eq(9),
        hole.eq(14),
        hole.eq(19)
    ],
    [
        hole.eq(5),
        hole.eq(10),
        hole.eq(15),
        hole.eq(20)
    ],
    [
        hole.eq(6),
        hole.eq(13),
        hole.eq(20),
        hole.eq(27)
    ],
    [
        hole.eq(7),
        hole.eq(14),
        hole.eq(21),
        hole.eq(28)
    ],
    [
        hole.eq(8),
        hole.eq(15),
        hole.eq(22),
        hole.eq(29)
    ],
    [
        hole.eq(9),
        hole.eq(14),
        hole.eq(19),
        hole.eq(24)
    ],
    [
        hole.eq(0),
        hole.eq(7),
        hole.eq(14),
        hole.eq(21)
    ],
    [
        hole.eq(10),
        hole.eq(15),
        hole.eq(20),
        hole.eq(25)
    ],
    [
        hole.eq(11),
        hole.eq(16),
        hole.eq(21),
        hole.eq(26)
    ],
    [
        hole.eq(12),
        hole.eq(19),
        hole.eq(26),
        hole.eq(33)
    ],
    [
        hole.eq(13),
        hole.eq(20),
        hole.eq(27),
        hole.eq(34)
    ],
    [
        hole.eq(14),
        hole.eq(21),
        hole.eq(28),
        hole.eq(35)
    ],
    [
        hole.eq(15),
        hole.eq(20),
        hole.eq(25),
        hole.eq(30)
    ],
    [
        hole.eq(16),
        hole.eq(21),
        hole.eq(26),
        hole.eq(31)
    ],
    [
        hole.eq(17),
        hole.eq(22),
        hole.eq(27),
        hole.eq(32)
    ],
    [
        hole.eq(18),
        hole.eq(25),
        hole.eq(32),
        hole.eq(39)
    ],
    [
        hole.eq(19),
        hole.eq(26),
        hole.eq(33),
        hole.eq(40)
    ],
    [
        hole.eq(20),
        hole.eq(27),
        hole.eq(34),
        hole.eq(41)
    ],
    [
        hole.eq(21),
        hole.eq(26),
        hole.eq(31),
        hole.eq(36)
    ],
    [
        hole.eq(22),
        hole.eq(27),
        hole.eq(32),
        hole.eq(37)
    ],
    [
        hole.eq(23),
        hole.eq(28),
        hole.eq(33),
        hole.eq(38)
    ],
];
